# Generated by Django 4.2.1 on 2024-08-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
