# Generated by Django 4.2.1 on 2024-08-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_register_age_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='repassword',
            new_name='username',
        ),
    ]
