# Generated by Django 4.2.1 on 2024-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
