# Generated by Django 4.2.1 on 2024-08-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password2',
        ),
    ]
