# Generated by Django 4.2.1 on 2024-08-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_remove_register_email_remove_register_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
