# Generated by Django 4.2.1 on 2024-08-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_register_age_register_email_register_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
    ]
