# Generated by Django 4.2.1 on 2024-09-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0011_remove_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password2',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
