# Generated by Django 4.2.1 on 2024-09-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_remove_register_password1_remove_register_password2_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='login',
        ),
    ]
