# Generated by Django 4.2.1 on 2024-09-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_register_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
