# Generated by Django 4.2.1 on 2024-09-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_remove_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='user',
        ),
    ]
