# Generated by Django 4.2.1 on 2024-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_rename_username_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='password2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
